name: startpage
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  cryptography: ^2.7.0
  file_picker: ^9.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  http: ^1.3.0
  image_network: ^2.6.0
  intl: ^0.19.0
  path: ^1.9.0
  test: ^1.25.7
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
